### ISSUE TITLE
server error when reply contains special characters

### ISSUE THREAD

**Issue by rsebbe** [OctopusDeploy/TenderSmash#2]
just tried your front-end. It's very promising (speed).

I'm getting server error 500 when the reply has special characters (French's "àéù" for instance). I'm trying to find a workaround, but I'm not fluent at all all with node.js / Angular. Could you please suggest some clues to solve this?

Thank you.

**Comment by droyad** [comment]
Sorry, but we were not monitoring this repo for issues until now. Are you still using the app? If so it this still a problem?
